### ISSUE TITLE
ERROR: LoadError: UndefVarError: Associative not defined

### ISSUE THREAD

**Issue by matbesancon** [lwabeke/Unmarshal.jl#20]
Happens while testing the package on julia 1.0 
This looks fixed on master, so a new release will make Unmarshal 1.0-compatible :)

**Comment by lwabeke** [comment]
I believe it was released, but broke when I tried to roll-out a bugfix for v0.6.
Trying to tag a new version again.

**Comment by rwfocke** [comment]
Julia 1.0 on my machine pulls tag v0.1.3, and not v0.2.0 where this issue was fixed.

attempting:
pkg> add Unmarshal@0.2
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Unmarshal [cbff2730]:
 Unmarshal [cbff2730] log:
 ├─possible versions are: [0.0.1-0.0.5, 0.1.0-0.1.1, 0.1.3] or uninstalled
 ├─restricted to versions * by BRDF [4e1d8c96], leaving only versions [0.0.1-0.0.5, 0.1.0-0.1.1, 0.1.3]
 │ └─BRDF [4e1d8c96] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─BRDF [4e1d8c96] is fixed to version 0.1.0
 └─restricted to versions 0.2 by an explicit requirement — no versions left

**Comment by lwabeke** [comment]
Julia 0.7 and 1.0 now seem to pull Unmarshal v0.2.1 by default, which should fix these issues. 
Should hopefully be no need to be pulling master anymore.
Please reopen if not the case.
